name: Node.js CI

on:
  push:
    branches:
      - '*'
    # Skip WIPs
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yml'
    # Skip duplication for pull requests to develop, master, v1.x
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yml'
    branches:
      - develop
      - master
      - v1.x

jobs:
  preinstall:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm ci --cache .npm --prefer-offline
          npm install -g gulp-cli
          npm install
          gulp -f devSetup.gulpfile.js

  lint:
    runs-on: ubuntu-latest
    needs: preinstall
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Run linter
        run: gulp lint

  build:
    runs-on: ubuntu-latest
    needs: preinstall
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Build project
        run: gulp build

  pack-deploy-release:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Deploy release
        run: |
          gulp -f devSetup.gulpfile.js
          gulp deploy --buildNum=$GITHUB_REF

      # Run this job only for tags and the master branch
    if: |
      github.event_name == 'push' && (github.ref_type == 'tag' || github.ref == 'refs/heads/master')

  pack-deploy-nightly:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Deploy nightly
        run: |
          gulp -f devSetup.gulpfile.js
          gulp packages --nightly --buildNum=$GITHUB_SHA
          gulp deployItchOnly --nightly --buildNum=$GITHUB_SHA

      # Run this job only for the develop branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
